export interface INave {
    id: number,
    foto: string,
    name: string,
    model: string,
    manufacturer: string,
    cost_in_credits: number,
    length: number,
    max_atmosphering_speed: number,
    crew: string,
    passengers: number,
    cargo_capacity: number,
    consumables: string,
    hyperdrive_rating: string,
    MGLT: string,
    starship_class: string,
    pilots: [],
    films: [],
    created: Date | undefined,
    edited: Date | undefined,
    url: string
}
